export const SITE = {
  website: "https://nihildigit.dev/",
  author: "NihilDigit",
  profile: "https://github.com/NihilDigit",
  desc: "Undergraduate researcher working on edge AI and video systems.",
  title: "NihilDigit",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 12,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Shanghai",
} as const;
